config/routes.rb
TrelloClone::Application.routes.draw do
  root to: 'static_pages#root'
  
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]
  
  namespace :api, defaults: { format: :json } do
    resources :boards, except: [:new, :edit]
    resources :lists, except: [:index, :new, :edit]
    resources :cards, except: [:index, :new, :edit]
    resources :board_memberships, only: [:create, :destroy]
  end
end

app/models/board.rb
class Board < ActiveRecord::Base
  validates :title, :user, presence: true
  
  belongs_to :user
  has_many :lists, dependent: :destroy
  has_many :board_memberships, dependent: :destroy
  has_many :members, through: :board_memberships, source: :user
end

app/models/board_membership.rb
class BoardMembership < ActiveRecord::Base
  validates :user_id, uniqueness: {scope: :board_id}
  
  belongs_to :user
  belongs_to :board
end

app/models/card.rb
class Card < ActiveRecord::Base
  validates :title, :list, :ord, presence: true
  
  belongs_to :list
end

app/models/list.rb
class List < ActiveRecord::Base
  validates :title, :board, :ord, presence: true
  
  belongs_to :board
  has_many :cards, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, :session_token, :password_digest, presence: true
  validates :email, :session_token, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }
  
  has_many :boards
  has_many :board_memberships
  has_many :memberships, through: :board_memberships, source: :board
  
  attr_reader :password
  
  after_initialize :ensure_session
  
  def self.new_token
    SecureRandom.urlsafe_base64(16)
  end
  
  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return nil unless user && user.valid_password?(password)
    user
  end
  
  def all_boards()
    Board.joins(
         "LEFT OUTER JOIN board_memberships ON boards.id = board_memberships.board_id")
         .where(
         "boards.user_id = :user_id OR board_memberships.user_id = :user_id",
         {user_id: self.id}).distinct("boards.id")
  end
  
  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end
  
  def valid_password?(password)
    BCrypt::Password.new(self.password_digest) == password
  end
  
  def reset_token!
    self.session_token = self.class.new_token
    self.save!
    self.session_token
  end
  
  private
  def ensure_session
    self.session_token ||= self.class.new_token
  end
end

app/controllers/api/api_controller.rb
module Api
  class ApiController < ApplicationController
    
  end
end

app/controllers/api/board_memberships_controller.rb
module Api
  class BoardMembershipsController < ApiController
    def create
      user = User.find_by_email(params[:email])
      
      if user
        user_id = user.id
      
        @membership = BoardMembership.new(board_id: member_params[:board_id], user_id: user_id)
      
        if @membership.save
          render json: @membership
        else
          render json: @membership.errors.full_messages, status: :unprocessable_entity
        end
      end
    end
    
    def destroy
      membership = BoardMembership.find(params[:id])
      membership.destroy
      render json: {}
    end
    
    private
    
    def member_params
      params.require(:board_membership).permit(:board_id, :user_id, :email)
    end
  end
end

app/controllers/api/boards_controller.rb
module Api
  class BoardsController < ApiController
    def index
      @boards = current_user.all_boards
      render json: @boards
    end
    
    def show
      @board = current_user.all_boards.find(params[:id])
      render :show
    end
    
    def create
      board = current_user.boards.new(board_params)
      
      if board.save
        render json: board
      else
        render json: board.errors.full_messages, status: :unprocessable_entity
      end
    end
    
    def update
      board = current_user.boards.find(params[:id])
      
      if board.update_attributes(params[:board])
        render json: board
      else
        render json: board.errors.full_messages, status: :unprocessable_entity
      end
    end
    
    def destroy
      board = current_user.boards.find(params[:id])
      board.try(:destroy)
      render json: @boards
    end
    
    private
    
    def board_params
      params.require(:board).permit(:title)
    end
  end
end

app/controllers/api/cards_controller.rb
module Api
  class CardsController < ApiController
    def show
      @card = Card.find(params[:id])
      render json: @card
    end
    
    def create
      card = Card.new(card_params)
      
      if card.save
        render json: card
      else
        render json: card.errors.full_messages, status: :unprocessable_entity
      end
    end
    
    def update
      card = Card.find(params[:id])
      
      if card.update_attributes(card_params)
        render json: card
      else
        render json: card.errors.full_messages, status: :unprocessable_entity
      end
    end
    
    def destroy
      card = Card.find(params[:id])
      card.destroy
      render json: {}
    end
    
    private
    
    def card_params
      params.require(:card).permit(:title, :list_id, :ord, :content)
    end
  end
end

app/controllers/api/lists_controller.rb
module Api
  class ListsController < ApiController
    def show
      @list = List.find(params[:id])
      render json: @list
    end
    
    def create
      list = List.new(list_params)
            
      if list.save
        render json: list
      else
        render json: list.errors.full_messages, status: :unprocessable_entity
      end
    end
    
    def update
      list = List.find(params[:id])
      
      if list.update_attributes(list_params)
        render json: list
      else
        render json: list.errors.full_messages, status: :unprocessable_entity
      end
    end
    
    def destroy
      list = List.find(params[:id])
      list.destroy
      render json: {}
    end
    
    private
    
    def list_params
      params.require(:list).permit(:title, :board_id, :ord)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  helper_method :current_user, :signed_in?
  
  private
  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end
  
  def signed_in?
    !!current_user
  end
  
  def sign_in(user)
    @current_user = user
    session[:session_token] = user.reset_token!
  end
  
  def sign_out
    current_user.try(:reset_token!)
    session[:session_token] = nil
  end
  
  def require_user!
    redirect_to new_session_url unless signed_in?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by_credentials(
      params[:user][:email],
      params[:user][:password]
    )
    
    if user.save
      sign_in(user)
      redirect_to root_url
    else
      flash.now[:errors] = ["Invalid email or password"]
      render :new
    end
  end
  
  def destroy
    sign_out
    redirect_to new_session_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :require_user!

  def root
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
  
  def create
    @user = User.new(user_params)
    
    if @user.save
      sign_in(@user)
      redirect_to root_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def authenticate
    "<input
        type=\"hidden\"
        name=\"authenticity_token\"
        value=\"#{form_authenticity_token}\">".html_safe
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_errors.html.erb
<%= flash[:errors].join("<br>").html_safe if flash[:errors]%>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="">Trello Clone</a>
    </div>
    
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav navbar-right">
    
      <li><%= link_to "Sign in", new_session_url %></li>
      <li><%= link_to "Sign up", new_user_url %></li>
    </ul>
  </div>   
  </div>
</nav>

    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TrelloClone</title>
  <script>FORM_AUTH_TOKEN = "<%= form_authenticity_token %>"</script>
  <%= stylesheet_link_tag  "application", media: "all"  %>
  <%= javascript_include_tag "application" %>    
  <%= csrf_meta_tags %>
  
</head>
<body>
  

      <%= yield %>
  
  
</body>
</html>

app/views/static_pages/root.html.erb
<div class="containter">
  <div id="navbar-bb"></div>
  <div class="row"></div>
  <div id="content" class="col-sm-12 white-panel"></div>
</div>

<script>

var currentUserId = <%= current_user.id %>
var currentUserEmail = '<%= current_user.email %>'

TrelloClone.currentUserId = currentUserId
TrelloClone.currentUserEmail = currentUserEmail

$(TrelloClone.initialize({
  $main: $('#content'),
  $navbar: $('#navbar-bb')
}));
</script>

app/views/users/new.html.erb
<%= render partial: "layouts/header" %>

<%= render "layouts/errors" %>


<div class="row">
  <div class="col-md-4 col-md-offset-4 landing">
  <h1>Sign Up</h1>
    <form action ="/users" method="post" class="margin-base-vertical">
      <%= authenticate %>
      <label>Email<br>
        <input type="text" 
               name="user[email]" 
               placeholder="Enter Email">
      </label><br><br>
  
      <label>Password<br>
        <input type="password"
               name="user[password]"
               placeholder="Enter Email">
      </label><br><br>
      <input type="submit" value="Submit" class="btn btn-custom-india-home">
    </form>
  </div>
</div>